spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - Path=/employee-service/**
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/product-service/**
          - id: produce-service
            uri: lb://produce-service
            predicates:
              - Path=/produce-service/**
          - id: business-service
            uri: lb://business-service
            predicates:
              - Path=/business-service/**
  datasource:
    url: jdbc:sqlserver://localhost:1499;databaseName=demo2;trustServerCertificate=true
    username: sa
    password: E=MC2kien0101535971
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    root: INFO
server:
  address: 0.0.0.0

